# https://andrijan.dev/blog/how-to-set-up-netlify-cms-with-astro/
backend:
  # Use netlify identity as backend
  # name: git-gateway
  name: github
  repo: jackie4u/resume-online
  branch: main
  
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

site_url: https://resume-vackar.netlify.app/
display_url: https://resume-vackar.netlify.app/
# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

# publish_mode: editorial_workflow
collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Meta Data"
        name: "metadata"
        file: "src/data/metadata.json"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Description, name: description, widget: string }
          - label: "Author"
            name: "author"
            widget: "object"
            collapsed: false
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Email, name: email, widget: string }
              - { label: Address, name: address, widget: string }
              - { label: Socials, name: socials, widget: string }
